### PR TITLE
add Home page

### PR DESCRIPTION
**Pull request by hsnice16**
PR for the Home page of the Quiz app.

UX Live: https://marvelsquiz-home.netlify.app/

marvelsQuiz

### CODE REVIEW

**Review by Maianki — APPROVED** [review]
Looks good Himanshu.

**Review by vrinda-mahajan — APPROVED** [review]
The code is clean. Good to merge👍

**Review by anik31 — APPROVED** [review]
Code & UI both are good. Amazing work

**Comment by hsnice16** [comment]
Thank you, guys, for reviewing this.

**Pull request merged**
