### PR TITLE
add Rules page for each category

### PR DESCRIPTION
**Pull request by hsnice16**
Changes done in this PR are -

- added GIF on the Home
image

- made Rules page for each category (UX is same, only category name changes)
image

Live: https://marvelsquiz-rules.netlify.app/

Please review and give your feedback.

### CODE REVIEW

**Review by Dev-AkshatGupta — APPROVED** [review]
Seems great to me to be merged

**Review by zoef-yt — APPROVED** [review]
Good to merge.

**Review by BalajiHarinath — APPROVED** [review]
Very nicely done. Liked the UI.

**Comment by hsnice16** [comment]
Thank you everyone for reviewing this.

**Pull request merged**
